### ISSUE TITLE
新建分类之后在分类下方新建文章无法加载出来

### ISSUE THREAD

**Issue by fueen** [dewjohn/hexo-theme-Klise#4]
新建分类之后在分类下方新建文章无法加载出来，
主题yml配置为
# main menu navigation
menu:
  Home: / || 主页
  Life: /life/ || 生活
  Skill: /skill/ || 技术
  About: /about/ || 关于
  categories: /categories/ || categories

分类在页面上能够加载出来，但是在source下方创建相关文件夹之后创建文章后界面无法加载文章，后缀为md文章如下

---
title: 生活
date: 2023-03-28 10:03:24
categories: categories
---
sss

**Comment by dewjohn** [comment]
请告诉我报错f12报错信息

**Comment by dewjohn** [comment]
另外呢，Category页面及其简陋，建议用归档页面 
在主题配置文件相应位置
```
menu:
  Home: / || Home
  About: /about/ || About
  Archives: /archives/ || Archives  # 加上这行
```

demo地址 [https://dewjohn.github.io/archives/](https://dewjohn.github.io/archives/)
