### ISSUE TITLE
Home 目录以及 Archives 目录下没有显示分页按钮

### ISSUE THREAD

**Issue by xxxsalted** [dewjohn/hexo-theme-Klise#8]
# 问题
文章超过十篇之后，Home 目录以及 Archives 目录下没有显示【下一页】按钮。
![image](https://github.com/dewjohn/hexo-theme-Klise/assets/75345234/f3438035-b723-475f-9df6-b368ba046530)
![image](https://github.com/dewjohn/hexo-theme-Klise/assets/75345234/73a54e12-3831-4a14-a016-f278db94eee3)

但是生成的 public 目录下有生成 page 目录，里面是第二页的内容：
![image](https://github.com/dewjohn/hexo-theme-Klise/assets/75345234/5085d1f1-b2ea-4f50-aa99-04f8c5310174)
![image](https://github.com/dewjohn/hexo-theme-Klise/assets/75345234/5a788479-af05-46d7-8054-c002db21a02a)

# 配置文件
主目录下的 _config.yml 文件关于分页的内容如下：
```
index_generator:
  path: ''
  per_page: 10
  order_by: -date
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
```

# hexo 版本及其他包版本
hexo: 7.2.0
hexo-cli: 4.3.2
os: win32 10.0.19045 undefined
node: 18.20.0
acorn: 8.10.0
ada: 2.7.6
ares: 1.27.0
base64: 0.5.2
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 44.1
icu: 74.2
llhttp: 6.1.0
modules: 108
napi: 9
nghttp2: 1.57.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.13+quic
simdutf: 4.0.8
tz: 2024a
undici: 5.28.3
unicode: 15.1
uv: 1.44.2
uvwasi: 0.0.19
v8: 10.2.154.26-node.36
zlib: 1.3.0.1-motley
